/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import java.util.HashMap;
import javax.swing.JOptionPane;
import model.MySQL;

/**
 *
 * @author kguna
 */
public class editSubject extends javax.swing.JFrame {

    /**
     * Creates new form editSubject
     */
    public editSubject(HashMap<String,String> x) {
        
        initComponents();
        
        subjectId.setText(x.get("subjectId"));
        subjectDescription.setText(x.get("description"));
        subjectName.setText(x.get("subject"));
        subjectPrice.setText(x.get("price"));
        subjectName.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        subjectDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        subjectPrice = new javax.swing.JTextField();
        subjectName = new javax.swing.JTextField();
        editSubjectButton = new javax.swing.JButton();
        subjectId = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setAlwaysOnTop(true);
        setPreferredSize(new java.awt.Dimension(535, 557));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel28.setFont(new java.awt.Font("Arial", 1, 48)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(153, 204, 255));
        jLabel28.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel28.setText("Edit Subject");
        jPanel1.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 380, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Subject Name");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 137, 135, 32));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Description");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 237, 135, -1));

        subjectDescription.setColumns(20);
        subjectDescription.setRows(5);
        jScrollPane1.setViewportView(subjectDescription);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 187, 314, 137));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Price");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(25, 342, 135, 36));

        subjectPrice.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(subjectPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 342, 314, 36));

        subjectName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(subjectName, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 135, 314, 34));

        editSubjectButton.setBackground(new java.awt.Color(0, 0, 102));
        editSubjectButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        editSubjectButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/edit.png"))); // NOI18N
        editSubjectButton.setText("  Edit Subject");
        editSubjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editSubjectButtonActionPerformed(evt);
            }
        });
        jPanel1.add(editSubjectButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(155, 427, 224, 59));

        subjectId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(subjectId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 50, 60, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowActivated

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        
        Dashboard.editClassDashboardBtn.setVisible(false);
        Dashboard.addClassDashboardBtn.setVisible(false);
        Dashboard.editSubjectDashboardBtn.setVisible(false);
        Dashboard.addSubjectDashboardBtn.setVisible(false);
        
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // TODO add your handling code here:
        
        Dashboard.editClassDashboardBtn.setVisible(true);
        Dashboard.addClassDashboardBtn.setVisible(true);
        Dashboard.editSubjectDashboardBtn.setVisible(true);
        Dashboard.addSubjectDashboardBtn.setVisible(true);
        
    }//GEN-LAST:event_formWindowClosed

    private void editSubjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editSubjectButtonActionPerformed
        // TODO add your handling code here:
        
        
        String description = subjectDescription.getText();
        String subjectSno = subjectId.getText();
        String price = subjectPrice.getText();

         if (description.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Add a Description", "Warning", JOptionPane.WARNING_MESSAGE);
        } else if (price.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please Add Price", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            JOptionPane.showMessageDialog(this, "Successfully Updated", "Updated", JOptionPane.INFORMATION_MESSAGE);

            try {

                MySQL.execute("UPDATE `subject` SET `description`='"+description+"',`price`='"+price+"' WHERE `subno`='" + subjectSno + "'  " );

            } catch (Exception e) {
                e.printStackTrace();
            }

            this.dispose();
            Dashboard.subjectDetailTable.setEnabled(true);

        }
        
    }//GEN-LAST:event_editSubjectButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(editSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(editSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(editSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(editSubject.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new editSubject().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editSubjectButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea subjectDescription;
    private javax.swing.JLabel subjectId;
    private javax.swing.JTextField subjectName;
    private javax.swing.JTextField subjectPrice;
    // End of variables declaration//GEN-END:variables
}
